create extension if not exists "pgcrypto";

insert into quests (day_number, title, subtitle, description, tier, xp_value, is_boss) values
(1, 'Hello, World!', 'Your first Python spell', 'Print Hello World and learn how to run a Python script.', 'beginner', 25, false),
(2, 'Simple print statements', 'Show text on screen', 'Use print() to display a few messages.', 'beginner', 25, false),
(3, 'Variables', 'Store values', 'Save a name, age, or favorite color in a variable.', 'beginner', 25, false),
(4, 'Input basics', 'Talk to the user', 'Ask the user for their name and print it back.', 'beginner', 25, false),
(5, 'Numbers', 'Simple math', 'Add and subtract a few numbers in Python.', 'beginner', 25, false),
(6, 'Strings', 'Work with text', 'Combine text and try a few simple string methods.', 'beginner', 25, false),
(7, 'Mini challenge 1', 'First checkpoint', 'Build a tiny greeting script using print and input.', 'boss', 100, true),
(8, 'Lists', 'Store a few items', 'Create a list and print each item.', 'beginner', 25, false),
(9, 'If statements', 'Make choices', 'Write a simple if/else program.', 'beginner', 25, false),
(10, 'Simple loops', 'Repeat actions', 'Use a for loop to print something several times.', 'beginner', 25, false),
(11, 'While loops', 'Keep going', 'Run code until a condition changes.', 'beginner', 25, false),
(12, 'Dictionaries', 'Label data', 'Store information with key and value pairs.', 'beginner', 25, false),
(13, 'Simple functions', 'Reuse code', 'Put repeated steps into a function.', 'beginner', 25, false),
(14, 'Mini challenge 2', 'Second checkpoint', 'Combine variables, input, and conditionals in a small script.', 'boss', 100, true),
(15, 'Debugging', 'Fix mistakes', 'Read error messages and correct a few bugs.', 'beginner', 25, false),
(16, 'Lists in depth', 'Work with more items', 'Add, remove, and loop through list values.', 'beginner', 25, false),
(17, 'More strings', 'Clean text', 'Use strip, split, replace, and join.', 'beginner', 25, false),
(18, 'More functions', 'Better reuse', 'Pass values into functions and return answers.', 'beginner', 25, false),
(19, 'Files', 'Save and load', 'Write a little text to a file and read it back.', 'beginner', 25, false),
(20, 'Errors and try/except', 'Stay calm', 'Handle mistakes without crashing.', 'beginner', 25, false),
(21, 'Mini challenge 3', 'Third checkpoint', 'Build a tiny quiz question and score it.', 'boss', 100, true),
(22, 'Modules', 'Use built-ins', 'Import a Python module and use one function.', 'beginner', 25, false),
(23, 'Project planning', 'Prepare to build', 'Choose a small final project and sketch it out.', 'beginner', 25, false),
(24, 'Classes basics', 'Objects', 'See how classes create reusable objects.', 'beginner', 25, false),
(25, 'Capstone helpers', 'Build a demo', 'Use what you learned to make a tiny app.', 'beginner', 25, false),
(26, 'Review day', 'Practice', 'Repeat the basics and strengthen weak spots.', 'beginner', 25, false),
(27, 'Final mini project', 'Fourth checkpoint', 'Make a small Python app with input and output.', 'boss', 100, true),
(28, 'Celebrate and continue', 'You are ready', 'Review your progress and plan the next step.', 'beginner', 25, false)
on conflict (day_number) do update set
  title = excluded.title,
  subtitle = excluded.subtitle,
  description = excluded.description,
  tier = excluded.tier,
  xp_value = excluded.xp_value,
  is_boss = excluded.is_boss;
