create extension if not exists "pgcrypto";

insert into quests (day_number, title, subtitle, description, tier, xp_value, is_boss) values
(1, 'Welcome to Python', 'Get oriented', 'Learn what Python is, how the course works, and how to run a first script.', 'beginner', 50, false),
(2, 'Print and comments', 'Your first tools', 'Use print(), add comments, and understand simple script structure.', 'beginner', 50, false),
(3, 'Variables', 'Store information', 'Create variables and use them to remember names, numbers, and text.', 'beginner', 50, false),
(4, 'Input basics', 'Talk to the player', 'Use input() and show simple output back to the screen.', 'beginner', 50, false),
(5, 'Numbers', 'Simple math', 'Add, subtract, multiply, and divide with Python values.', 'beginner', 50, false),
(6, 'Strings', 'Text handling', 'Combine text, add spaces, and work with simple string methods.', 'beginner', 50, false),
(7, 'Mini challenge 1', 'First checkpoint', 'Make a tiny script that asks for a name and greets the learner.', 'boss', 150, true),
(8, 'Lists', 'A collection of items', 'Store several things together and read them back.', 'beginner', 50, false),
(9, 'If statements', 'Decisions', 'Let your program choose between simple paths.', 'beginner', 50, false),
(10, 'Loops', 'Repeat work', 'Run the same code more than once with for and while loops.', 'beginner', 50, false),
(11, 'Dictionaries', 'Labelled data', 'Store information with keys and values.', 'beginner', 50, false),
(12, 'Simple functions', 'Reuse code', 'Wrap repeated steps into a function.', 'beginner', 50, false),
(13, 'Debugging', 'Fix mistakes', 'Read errors and correct small problems.', 'beginner', 50, false),
(14, 'Mini challenge 2', 'Second checkpoint', 'Combine variables, input, and conditionals in a tiny app.', 'boss', 150, true),
(15, 'Working with files', 'Save progress', 'Write simple text to a file and read it back.', 'beginner', 50, false),
(16, 'Modules', 'Use built-ins', 'Import useful Python tools and use them in your scripts.', 'beginner', 50, false),
(17, 'Lists in depth', 'Looping through data', 'Read, add, and update items in a list.', 'beginner', 50, false),
(18, 'More strings', 'Clean text', 'Use strip, split, replace, and join.', 'beginner', 50, false),
(19, 'More functions', 'Better reuse', 'Pass values into functions and return answers.', 'beginner', 50, false),
(20, 'Errors and try/except', 'Stay calm', 'Handle mistakes without crashing.', 'beginner', 50, false),
(21, 'Mini challenge 3', 'Third checkpoint', 'Build a small quiz question and score it.', 'boss', 150, true),
(22, 'Dictionaries in depth', 'Organize data', 'Use keys, values, and nested data structures.', 'beginner', 50, false),
(23, 'Project planning', 'Prepare to build', 'Choose a tiny final project and sketch it out.', 'beginner', 50, false),
(24, 'Classes basics', 'Objects', 'Introduce simple classes and object creation.', 'beginner', 50, false),
(25, 'Capstone helpers', 'Build a demo', 'Use the tools you learned to make something small.', 'beginner', 50, false),
(26, 'Review day', 'Go slower', 'Practice the weakest topics and repeat key ideas.', 'beginner', 50, false),
(27, 'Final mini project', 'Fourth checkpoint', 'Make a tiny Python app with input, decisions, and output.', 'boss', 150, true),
(28, 'Celebrate and continue', 'You are ready', 'Review what you learned and plan your next step.', 'beginner', 50, false)
on conflict (day_number) do update set
  title = excluded.title,
  subtitle = excluded.subtitle,
  description = excluded.description,
  tier = excluded.tier,
  xp_value = excluded.xp_value,
  is_boss = excluded.is_boss;
